module.exports = {
    pointerTypes: {
        '!': 'Antonym',
        '@': 'Hypernym',
        '@i': 'Instance Hypernym',
        '~': 'Hyponym',
        '~i': 'Instance Hyponym',
        '#m': 'Member holonym',
        '#s': 'Substance holonym',
        '#p': 'Part holonym',
        '%m': 'Member meronym',
        '%s': 'Substance meronym',
        '%p': 'Part meronym',
        '=': 'Attribute',
        '+': 'Derivationally related form',
        ';c': 'Domain of synset - TOPIC',
        '-c': 'Member of this domain - TOPIC',
        ';r': 'Domain of synset - REGION',
        '-r': 'Member of this domain - REGION',
        ';u': 'Domain of synset - USAGE',
        '-u': 'Member of this domain - USAGE',
        '^': 'Also see',
        '&': 'Similar to',
        "$": "Verb group"
    },
    posTags: [
        "CD",
        "FW",
        "JJ",
        "JJR",
        "JJS",
        "NN",
        "NNS",
        "RB",
        "RBR",
        "RBS",
        "RP",
        "SYM",
        "UH",
        "VB",
        "VBD",
        "VBG",
        "VBN",
        "VBP",
        "VBZ",
    ]
}